version: "3.7"

services:
    postgres:
        image: postgres:13.3-alpine
        volumes:
            - ./postgres-data:/var/lib/postgres
        environment:
            POSTGRES_PASSWORD: mysecretpassword
            POSTGRES_USER: postgres
            POSTGRES_DB: school_dev